import pandas as pd
import json
from tqdm.auto import tqdm
from pydantic import BaseModel
from typing import Literal
from dotenv import load_dotenv
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor

load_dotenv()
client = OpenAI()

# --- Define the judge output ---
class AnswerEvaluation(BaseModel):
    reasoning: str
    score: Literal["good", "bad"]

# --- Judge instructions ---
judge_instructions = """
You are an expert evaluator. You will be given:
1. A question from a student
2. The original answer from the knowledge base (ground truth)
3. An answer generated by an AI assistant

Your task is to decide if the AI answer is semantically equivalent to the original answer.

Rules:
- The AI answer does NOT need to be word-for-word identical
- It should convey the same key information
- Extra detail is fine as long as the core answer is correct
- Mark 'bad' only if the AI answer is wrong or misses the key point

Be fair and focus on correctness, not style.
""".strip()

judge_prompt = """
Question: {question}

Original Answer (ground truth):
{answer_orig}

AI Answer:
{answer_llm}
""".strip()

# --- Helper function ---
def llm_structured_retry(instructions, user_prompt, output_type, max_retries=3):
    import time
    for attempt in range(max_retries):
        try:
            messages = [
                {"role": "developer", "content": instructions},
                {"role": "user", "content": user_prompt}
            ]
            response = client.responses.parse(
                model="gpt-5.4-mini",
                input=messages,
                text_format=output_type
            )
            return response.output_parsed
        except Exception:
            if attempt == max_retries - 1:
                raise
            time.sleep(2 ** attempt)

# --- Judge one answer ---
def judge_answer(question, answer_orig, answer_llm):
    prompt = judge_prompt.format(
        question=question,
        answer_orig=answer_orig,
        answer_llm=answer_llm
    )
    result = llm_structured_retry(judge_instructions, prompt, AnswerEvaluation)
    return result.score

# --- Judge all answers ---
def evaluate_answers(df, answer_col):
    scores = []
    for _, row in tqdm(df.iterrows(), total=len(df)):
        score = judge_answer(
            row["question"],
            row["answer_orig"],
            row[answer_col]
        )
        scores.append(score)
    df["judge_score"] = scores
    return df

# --- Load the data ---
df_rag = pd.read_csv("GroundTruth/rag_answers.csv")
df_agent = pd.read_csv("GroundTruth/agent_answers.csv")

print(f"Loaded {len(df_rag)} RAG answers and {len(df_agent)} agent answers")

# --- Judge both ---
print("\nJudging RAG answers...")
df_rag = evaluate_answers(df_rag, "answer_llm")

print("\nJudging Agent answers...")
df_agent = evaluate_answers(df_agent, "answer_agent")

# --- Calculate scores ---
rag_good = (df_rag["judge_score"] == "good").sum()
agent_good = (df_agent["judge_score"] == "good").sum()

rag_total = len(df_rag)
agent_total = len(df_agent)

rag_pct = rag_good / rag_total * 100
agent_pct = agent_good / agent_total * 100

# --- Print results ---
print("\n" + "=" * 50)
print("📊 EVALUATION RESULTS")
print("=" * 50)
print(f"RAG Approach:    {rag_good}/{rag_total} good ({rag_pct:.1f}%)")
print(f"Agent Approach:  {agent_good}/{agent_total} good ({agent_pct:.1f}%)")
print("=" * 50)

if rag_pct > agent_pct:
    print("🏆 WINNER: RAG Approach (fp_rag_helper.py)")
elif agent_pct > rag_pct:
    print("🏆 WINNER: Agentic Approach (agentic_assistant.py)")
else:
    print("🤝 TIE! Both approaches performed equally well.")

# --- Save judged results ---
df_rag.to_csv("GroundTruth/rag_judged.csv", index=False)
df_agent.to_csv("GroundTruth/agent_judged.csv", index=False)
print("\nSaved judged results to GroundTruth/")